name: CI

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push AI Service
        uses: docker/build-push-action@v5
        with:
          context: ./ai_service
          push: true
          provenance: false
          sbom: false
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/ai-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/ai-service:buildcache,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ai-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ai-service:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/ai-service:run-${{ github.run_number }}

      - name: Build and Push Webhook Service
        uses: docker/build-push-action@v5
        with:
          context: ./webhook_service
          push: true
          provenance: false
          sbom: false
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/webhook-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/webhook-service:buildcache,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/webhook-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/webhook-service:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/webhook-service:run-${{ github.run_number }}

      - name: Build and Push Orchestrator
        uses: docker/build-push-action@v5
        with:
          context: ./orchestrator
          file: ./orchestrator/Dockerfile
          push: true
          provenance: false
          sbom: false
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/orchestrator:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/orchestrator:buildcache,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/orchestrator:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/orchestrator:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/orchestrator:run-${{ github.run_number }}
